openapi: 3.0.0
info:
  title: assets
  version: '1.0'
  contact:
    name: Josh Bregman
    url: 'https://github.com/jbregman/marvelstoplight'
    email: jbregman@gmail.com
  termsOfService: 'https://github.com/jbregman/marvelstoplight/README.MD'
  description: Assets API for Stratejm
servers:
  - url: 'http://localhost:3000'
    description: Dev
paths:
  /assets:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Asset'
              examples:
                example-1:
                  value:
                    - id: '2'
      operationId: get-assets
      parameters:
        - schema:
            type: string
          in: query
          name: query
          description: Query String for Assets
      description: This is the endpoint for getting assets
components:
  schemas:
    Asset:
      title: Asset
      type: object
      properties:
        id:
          type: string
      x-examples:
        Example Asset:
          id: '1'
      description: An asset in the system
  securitySchemes:
    API Key - 1:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: ''
          tokenUrl: ''
          refreshUrl: ''
          scopes: {}
      description: ''
